name: buid and push image to docker

on: push

jobs:

  build-container:

    runs-on: ubuntu-latest

    steps:
     - name : check out repo
       uses: actions/checkout@v3
       
     - name: Login to dockerhub
       uses: docker/login-action@v2
       with:
        username: ${{ secrets.DOCKERHUB_USERNAME  }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
     - name: Build and push Docker image
       uses: docker/build-push-action@v4
       with: 
        context: .
        push: true
        tags: naga44/testrepo:latest
        
       
